### ISSUE TITLE
Download test data

### ISSUE THREAD

**Issue by miyuxuezhe** [danich1/Spider-Pipeline#1]
When I download the sample data, I am prompted to enter a password, what should I do

**Comment by danich1** [comment]
>When I download the sample data, I am prompted to enter a password, what should I do

You can't download the data use the link in the text file. It's on University of Pennsylvania's cluster and I don't have access to it anymore. However, If you do need access to the data please contact the corresponding author on this [paper](https://www.nature.com/articles/ng.3852). Thanks.

**Comment by miyuxuezhe** [comment]
thanks
