### ISSUE TITLE
how to edit the scaffold_25678_47904_motif_list_v1.txt file?

### ISSUE THREAD

**Issue by miyuxuezhe** [danich1/Spider-Pipeline#2]
I have 40 protein sequences, and I find the motif of each sequence, but how do I name the first column?（A1 B1 C1 ...）

3. MANUAL CURATE MOTIFS
------------------------------------------------------------------------------------------------------
# Note the each line needs to be separated by a tab character!!
emacs 042215_meme_scaffold_25678_47904/scaffold_25678_47904_motif_list_v1.txt
A1  DSESSPSGEY
B1  DTGSYPTGEY
C1  DTYERSYYNGEN
D1  DTYSTESNNTESY
E1  NSESYITEEY

**Comment by danich1** [comment]
All you need to do for the text file is have it be the following:
label *press tab* sequence
label *press tab* sequence
...

Make sure the label is simple like a letter and number.

**Comment by miyuxuezhe** [comment]
ok
